// DO NOT EDIT THIS FILE
// This file is automatically generated by go-dsl.
// Rerun go-dsl to update the language.
// Warning: Files prefixed with 'dsl_' or 'template_' will be removed,
// any manual changes will be lost.

package language

import (
	"fmt"
)

type Text struct {
	Text  string
	Style *TextStyle
}

func (t *Text) String() string {
	return fmt.Sprintf("T(\"%s\" %s)", t.Text, t.Style.String())
}
