// DO NOT EDIT THIS FILE
// This file is automatically generated by go-dsl.
// Rerun go-dsl to update the language.
// Warning: Files prefixed with 'dsl_' or 'template_' will be removed,
// any manual changes will be lost.

package language

import (
	"fmt"
)

type NGon struct {
	Points []*Point
}

func (n *NGon) String() string {
	return fmt.Sprintf("N(%d points)", len(n.Points))
}

func (n *NGon) Delta(n2 NGon) *NGon {
	for i, p := range n.Points {
		n.Points[i] = p.Delta(n2.Points[i])
	}
	return n
}

func (n *NGon) Translate(x, y float64) *NGon {
	for _, p := range n.Points {
		p.Translate(x, y)
	}
	return n
}

func (n *NGon) Norm(x, y float64) *NGon {
	for _, p := range n.Points {
		p.Norm(x, y)
	}
	return n
}

func (n *NGon) Denorm(x, y float64) *NGon {
	for _, p := range n.Points {
		p.Denorm(x, y)
	}
	return n
}
