// DO NOT EDIT THIS FILE
// This file is automatically generated by go-dsl.
// Rerun go-dsl to update the language.
// Warning: Files prefixed with 'dsl_' or 'template_' will be removed,
// any manual changes will be lost.

package language

import (
	"fmt"
	"image/color"
)

type LineStyle struct {
	Thickness float64
	Color     *color.RGBA64
}

func (l *LineStyle) String() string {
	return fmt.Sprintf("LS(%.1f %v)", l.Thickness, l.Color)
}

type FillStyle struct {
	Color *color.RGBA64
}

func (f *FillStyle) String() string {
	return fmt.Sprintf("FS(%v)", f.Color)
}

type TextStyle struct {
	Family string
	Size   float64
	Color  *color.RGBA64
}

func (f *TextStyle) String() string {
	return fmt.Sprintf("TS(%v)", f.Color)
}
