// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApproveReviewQueueItem():Promise<boolean>;

export function BatchProgress():Promise<number>;

export function CancelRendering():Promise<void>;

export function FileToBase64(arg1:string,arg2:number,arg3:number):Promise<main.OpResult>;

export function LoadMultipleImages():Promise<main.OpResult>;

export function LoadMultipleInputImages():Promise<main.OpResult>;

export function NextReviewQueueItem():Promise<main.OpResult>;

export function OpenFile(arg1:string):Promise<main.OpResult>;

export function RejectReviewQueueItem():Promise<boolean>;

export function Run(arg1:string,arg2:Array<string>):Promise<main.OpResult>;

export function RunBatch(arg1:string,arg2:string,arg3:Array<any>,arg4:boolean):Promise<Record<string, string>>;

export function SaveFile(arg1:string,arg2:string):Promise<main.OpResult>;

export function SaveOutput():Promise<main.OpResult>;

export function SelectDirectory():Promise<main.OpResult>;
