// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveReviewQueueItem() {
  return window['go']['main']['App']['ApproveReviewQueueItem']();
}

export function BatchProgress() {
  return window['go']['main']['App']['BatchProgress']();
}

export function CancelRendering() {
  return window['go']['main']['App']['CancelRendering']();
}

export function FileToBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileToBase64'](arg1, arg2, arg3);
}

export function LoadMultipleImages() {
  return window['go']['main']['App']['LoadMultipleImages']();
}

export function LoadMultipleInputImages() {
  return window['go']['main']['App']['LoadMultipleInputImages']();
}

export function NextReviewQueueItem() {
  return window['go']['main']['App']['NextReviewQueueItem']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RejectReviewQueueItem() {
  return window['go']['main']['App']['RejectReviewQueueItem']();
}

export function Run(arg1, arg2) {
  return window['go']['main']['App']['Run'](arg1, arg2);
}

export function RunBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunBatch'](arg1, arg2, arg3, arg4);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveOutput() {
  return window['go']['main']['App']['SaveOutput']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
